spring.application.name=TaskManangementNotification

#Database Setup
spring.data.mongodb.database=notifdb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

#RabbitMQ Setup
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=pass
spring.rabbitmq.virtual-host=/
